import type { Metadata } from 'next';

// Vercel serves www.fleetos.se as the primary domain (fleetos.se redirects there), so every
// canonical, sitemap entry and structured-data URL must use the www host to match.
export const SITE_URL = 'https://www.fleetos.se';
export const SITE_NAME = 'FleetOS';

export const COMPANY = {
  legalName: 'DSE ENTERPRISE AB',
  orgNumber: '559510-0248',
  email: 'david@fleetos.se',
  instagram: 'https://www.instagram.com/fleetos.se/',
};

// Generated by src/app/opengraph-image.tsx. File-based OG images aren't inherited by child
// segments that set their own `openGraph`, so every page references it explicitly.
const OG_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'FleetOS – uthyrningssystem för maskiner, truckar och liftar',
};

export function absoluteUrl(path: string) {
  return path === '/' ? SITE_URL : `${SITE_URL}${path}`;
}

/**
 * Full metadata for a public marketing page. Next merges metadata shallowly, so a page that
 * sets its own `openGraph` loses the layout's siteName/locale — this builds the whole object
 * every time so each page gets a self-referencing canonical and consistent social tags.
 * `title` is the page-specific part; the root layout's template appends " | FleetOS".
 */
export function pageMetadata({
  path,
  title,
  description,
  absoluteTitle = false,
  noindex = false,
}: {
  path: string;
  title: string;
  description: string;
  absoluteTitle?: boolean;
  noindex?: boolean;
}): Metadata {
  const url = absoluteUrl(path);
  const fullTitle = absoluteTitle ? title : `${title} | ${SITE_NAME}`;
  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: 'website',
      locale: 'sv_SE',
      siteName: SITE_NAME,
      url,
      title: fullTitle,
      description,
      images: [OG_IMAGE],
    },
    twitter: { card: 'summary_large_image', title: fullTitle, description, images: [OG_IMAGE.url] },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
  };
}

export type Crumb = { name: string; path: string };

export function breadcrumbJsonLd(crumbs: Crumb[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: crumbs.map((c, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: c.name,
      item: absoluteUrl(c.path),
    })),
  };
}

export function faqJsonLd(faqs: { q: string; a: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map(({ q, a }) => ({
      '@type': 'Question',
      name: q,
      acceptedAnswer: { '@type': 'Answer', text: a },
    })),
  };
}

export function organizationJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    '@id': `${SITE_URL}/#organization`,
    name: SITE_NAME,
    legalName: COMPANY.legalName,
    url: SITE_URL,
    logo: `${SITE_URL}/logo.png`,
    email: COMPANY.email,
    identifier: { '@type': 'PropertyValue', propertyID: 'Organisationsnummer', value: COMPANY.orgNumber },
    address: { '@type': 'PostalAddress', addressCountry: 'SE' },
    sameAs: [COMPANY.instagram],
  };
}
