import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { calcRentalBreakdown } from '@/lib/utils';
import { NextResponse, type NextRequest } from 'next/server';
import type { InvoicePeriod, OrderArticle } from '@/lib/types';
import { LIMITS } from '@/lib/rate-limit';

const FORTNOX_API = 'https://api.fortnox.se/3';

async function getValidToken(orgId: string): Promise<string | null> {
  const admin = createAdminClient();
  const { data: integration } = await admin
    .from('integrations')
    .select('access_token, refresh_token, expires_at')
    .eq('organization_id', orgId)
    .eq('provider', 'fortnox')
    .single();

  if (!integration) return null;

  const expiresAt = new Date(integration.expires_at as string).getTime();
  if (Date.now() < expiresAt - 5 * 60 * 1000) return integration.access_token as string;

  const credentials = Buffer.from(
    `${process.env.FORTNOX_CLIENT_ID}:${process.env.FORTNOX_CLIENT_SECRET}`
  ).toString('base64');

  const res = await fetch('https://apps.fortnox.se/oauth-v1/token', {
    method: 'POST',
    headers: { 'Authorization': `Basic ${credentials}`, 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ grant_type: 'refresh_token', refresh_token: integration.refresh_token as string }),
  });
  if (!res.ok) return null;

  const tokens = await res.json();
  const newExpiresAt = new Date(Date.now() + tokens.expires_in * 1000).toISOString();
  await admin.from('integrations').update({
    access_token: tokens.access_token,
    refresh_token: tokens.refresh_token,
    expires_at: newExpiresAt,
    updated_at: new Date().toISOString(),
  }).eq('organization_id', orgId).eq('provider', 'fortnox');

  return tokens.access_token as string;
}

export async function POST(request: NextRequest) {
  try {
    const { orderId, periodId } = await request.json();
    if (!orderId || !periodId) return NextResponse.json({ error: 'orderId och periodId krävs' }, { status: 400 });

    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: 'Ej inloggad' }, { status: 401 });

    if (!await LIMITS.integration(user.id)) {
      return NextResponse.json({ error: 'För många förfrågningar. Försök igen om en minut.' }, { status: 429 });
    }

    const { data: profile } = await supabase.from('profiles').select('organization_id, cost_center').eq('id', user.id).single();
    const orgId = profile?.organization_id;
    const costCenter = (profile as { cost_center?: string | null } | null)?.cost_center ?? null;
    if (!orgId) return NextResponse.json({ error: 'Ingen organisation' }, { status: 400 });

    const token = await getValidToken(orgId);
    if (!token) return NextResponse.json({ error: 'Fortnox inte ansluten' }, { status: 400 });

    const admin = createAdminClient();
    const { data: orderRow } = await admin
      .from('orders')
      .select('*, customers(*)')
      .eq('id', orderId)
      .eq('organization_id', orgId)
      .single();

    if (!orderRow) return NextResponse.json({ error: 'Order hittades inte' }, { status: 404 });

    const invoicePeriods = (orderRow.invoice_periods as InvoicePeriod[]) ?? [];
    const period = invoicePeriods.find((p) => p.id === periodId);
    if (!period) return NextResponse.json({ error: 'Fakturaperiod hittades inte' }, { status: 404 });
    if (period.sentToAccounting) return NextResponse.json({ error: 'Perioden är redan skickad till Fortnox' }, { status: 400 });

    // Order-level extras flagged "first_invoice" bill once, on the order's earliest delfaktura.
    // Extras flagged "every_invoice" (e.g. insurance) bill the same line on every delfaktura.
    const isFirstPeriod = [...invoicePeriods].sort((a, b) => a.startDate.localeCompare(b.startDate))[0]?.id === period.id;
    const orderArticlesList = (orderRow.order_articles as OrderArticle[]) ?? [];
    const dueFirstInvoiceArticles = isFirstPeriod
      ? orderArticlesList.filter((a) => a.billing === 'first_invoice' && !a.billed)
      : [];
    const recurringArticles = orderArticlesList.filter((a) => a.billing === 'every_invoice');
    const dueArticles = [...dueFirstInvoiceArticles, ...recurringArticles];

    // If this period was generated by a machine swap, it billed the OUTGOING machine's usage —
    // describe that machine on the invoice, not whatever machine is currently on the order.
    const machineSwaps = (orderRow.machine_swaps as { invoicePeriodId?: string; fromMachineId: string }[]) ?? [];
    const swapForPeriod = machineSwaps.find((s) => s.invoicePeriodId === period.id);
    const effectiveMachineId = swapForPeriod?.fromMachineId ?? (orderRow.machine_id as string);
    const { data: machineRow } = await admin
      .from('machines')
      .select('name, brand, model, internal_code, serial_number')
      .eq('id', effectiveMachineId)
      .single();

    // Ensure Fortnox customer
    const customerRow = orderRow.customers as Record<string, unknown>;
    let fortnoxCustomerNumber = customerRow.fortnox_customer_number as string | null;

    if (!fortnoxCustomerNumber) {
      const res = await fetch(`${FORTNOX_API}/customers`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          Customer: {
            Name: customerRow.company_name,
            OrganisationNumber: customerRow.org_number || undefined,
            Email: customerRow.email || undefined,
            Phone1: customerRow.phone || undefined,
            Address1: customerRow.invoice_address || undefined,
          },
        }),
      });
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        return NextResponse.json({ error: `Kunde inte skapa kund: ${err?.ErrorInformation?.message ?? res.status}` }, { status: 500 });
      }
      const json = await res.json();
      fortnoxCustomerNumber = json.Customer?.CustomerNumber ?? null;
      if (fortnoxCustomerNumber) {
        await admin.from('customers').update({ fortnox_customer_number: fortnoxCustomerNumber }).eq('id', orderRow.customer_id);
      }
    }

    if (!fortnoxCustomerNumber) return NextResponse.json({ error: 'Kunde inte hämta kundnummer' }, { status: 500 });

    // Build machine description
    const machineParts = machineRow ? [
      machineRow.brand, machineRow.model, machineRow.name,
      machineRow.internal_code ? `(${machineRow.internal_code})` : null,
    ].filter(Boolean).join(' ') : 'Maskin';

    const chargeWeekends = (orderRow.charge_weekends as boolean) ?? false;
    const monthlyDiscount = (orderRow.monthly_discount as number) ?? 0;
    const weeklyDiscount = (orderRow.weekly_discount as number) ?? 0;
    const dailyDiscount = (orderRow.rental_discount as number) ?? 0;

    type FortnoxRow = { ArticleNumber?: string; Description: string; DeliveredQuantity: number; Price: number; Unit: string; Discount?: number };
    const orderRows: FortnoxRow[] = [];

    if (period.manualAmount) {
      // A person hand-edited this period's amount — send it exactly as-is, not recomputed.
      orderRows.push({
        Description: `Hyra - ${machineParts} - ${period.startDate} t.o.m. ${period.endDate}`,
        DeliveredQuantity: 1,
        Price: period.amount,
        Unit: 'st',
      });
    } else {
      const breakdown = calcRentalBreakdown(
        period.startDate, period.endDate, chargeWeekends,
        orderRow.daily_price as number, orderRow.weekly_price as number, orderRow.monthly_price as number,
      );

      if (breakdown.months > 0) {
        orderRows.push({
          Description: `${machineParts} - ${period.startDate} - ${period.endDate} (${breakdown.months} mån)`,
          DeliveredQuantity: breakdown.months,
          Price: orderRow.monthly_price as number,
          Unit: 'mån',
          ...(monthlyDiscount > 0 ? { Discount: monthlyDiscount } : {}),
        });
      }
      if (breakdown.weeks > 0) {
        orderRows.push({
          Description: `${machineParts} - veckor`,
          DeliveredQuantity: breakdown.weeks,
          Price: orderRow.weekly_price as number,
          Unit: 'vecka',
          ...(weeklyDiscount > 0 ? { Discount: weeklyDiscount } : {}),
        });
      }
      if (breakdown.days > 0 || orderRows.length === 0) {
        orderRows.push({
          Description: orderRows.length === 0
            ? `Hyra - ${machineParts} - ${period.startDate} t.o.m. ${period.endDate}`
            : `${machineParts} - dagar`,
          DeliveredQuantity: breakdown.days > 0 ? breakdown.days : 1,
          Price: orderRow.daily_price as number,
          Unit: 'dag',
          ...(dailyDiscount > 0 ? { Discount: dailyDiscount } : {}),
        });
      }
    }

    // Lookup rental article number
    if (orderRow.rental_article_id) {
      const { data: art } = await admin.from('articles').select('article_number').eq('id', orderRow.rental_article_id).single();
      if (art?.article_number) orderRows.forEach((r) => { r.ArticleNumber = art.article_number; });
    }

    // Append order-level extras due on this delfaktura (first-invoice and/or recurring ones)
    if (dueArticles.length > 0) {
      const { data: extraArtRows } = await admin
        .from('articles')
        .select('id, name, unit, article_number')
        .in('id', dueArticles.map((a) => a.articleId));
      const extraArticleLookup = Object.fromEntries((extraArtRows ?? []).map((a) => [a.id, a]));
      for (const extra of dueArticles) {
        const art = extraArticleLookup[extra.articleId];
        orderRows.push({
          ...(art?.article_number ? { ArticleNumber: art.article_number } : {}),
          Description: extra.description || art?.name || 'Artikel',
          DeliveredQuantity: extra.quantity,
          Price: extra.unitPrice,
          Unit: art?.unit ?? 'st',
          ...(extra.discountPercent ? { Discount: extra.discountPercent } : {}),
        });
      }
    }

    const fortnoxRes = await fetch(`${FORTNOX_API}/orders`, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        Order: {
          CustomerNumber: fortnoxCustomerNumber,
          OrderDate: new Date().toISOString().split('T')[0],
          OurReference: orderRow.order_number,
          YourOrderNumber: (orderRow.order_reference as string) || '',
          Comments: `Delfaktura ${period.startDate} - ${period.endDate}, order ${orderRow.order_number}`,
          ...(costCenter ? { CostCenter: costCenter } : {}),
          OrderRows: orderRows,
        },
      }),
    });

    if (!fortnoxRes.ok) {
      const errBody = await fortnoxRes.json().catch(() => ({}));
      const errMsg = errBody?.ErrorInformation?.message ?? JSON.stringify(errBody);
      return NextResponse.json({ error: `Fortnox: ${errMsg}` }, { status: 500 });
    }

    const fortnoxJson = await fortnoxRes.json();
    const fortnoxOrderNumber = fortnoxJson.Order?.DocumentNumber as string;

    // Mark period as sent, and any first_invoice extras just billed as such
    const updatedPeriods = invoicePeriods.map((p) =>
      p.id === periodId ? { ...p, fortnoxOrderNumber, sentToAccounting: true } : p
    );
    const updatedOrderArticles = dueFirstInvoiceArticles.length > 0
      ? orderArticlesList.map((a) => dueFirstInvoiceArticles.includes(a) ? { ...a, billed: true } : a)
      : orderArticlesList;
    await admin.from('orders').update({
      invoice_periods: updatedPeriods,
      ...(dueFirstInvoiceArticles.length > 0 ? { order_articles: updatedOrderArticles } : {}),
    }).eq('id', orderId);

    return NextResponse.json({ success: true, fortnoxOrderNumber });
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Okänt fel';
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
